import type { Metadata } from "next";
import "./globals.css";
import Top from "./Components/Top";
import Header from "./Components/Header";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Top />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
